INSERT INTO STUDENTS VALUES("4","JAANU","FEMALE","5"),("5","RAMYA","FEMALE","6");
INSERT INTO STUDENTS VALUES("6","HONEY","FEMALE","6");
SELECT * FROM MARKS;
SELECT * FROM STUDENTS;

ALTER TABLE STUDENTS ADD COLUMN AGE TINYINT NOT NULL;
--- CREATING BACKUP TABLE FOR STUDENTS
CREATE TABLE BACKUP_TABLE AS
SELECT * FROM STUDENTS;
SELECT * FROM BACKUP_TABLE;
DESC BACKUP_TABLE;
DESC STUDENTS;
CREATE TABLE STUDENT_INFO AS
SELECT STD_ID,STD_NAME,CLASS FROM STUDENTS;
SELECT * FROM STUDENT_INFO;
 -- CREATING A TABLE 6 TH CLAS STUDENT DATA
 CREATE TABLE CLASS_6 AS SELECT STD_ID,STD_NAME,CLASS FROM STUDENTS
WHERE CLASS=6;
SELECT * FROM CLASS_6;
CREATE TABLE CLASS_7 AS SELECT  STD_ID,STD_NAME,CLASS FROM STUDENTS 
WHERE CLASS=7;
SELECT * FROM CLASS_7;
SELECT * FROM STUDENTS;
SELECT * FROM CLASS_6
WHERE 1=0;
INSERT INTO STUDENTS VALUES("7","MAHA","FEMALE","7","22");
SELECT * FROM CLASS_7;
SELECT * FROM BACKUP_TABLE;
UPDATE STUDENTS SET CLASS = 7
WHERE STD_ID=1;
SELECT * FROM STUDENTS;
SELECT * FROM BACKUP_TABLE;
