-- Creating Movies Database
CREATE DATABASE IF NOT EXISTS MOVIES;
CREATE DATABASE SONGS;

-- SELECTING DATABASE
-- SYNTAX: USE DATABASE_NAME;
USE MOVIES;


-- REMOVE DATABASE SONGSS
DROP DATABASE IF EXISTS SONGS;
show databases;
