use movies;
create table IF NOT EXISTS MOVIE_TABLE(
S_NUM INT,
MOVIE_NAME VARCHAR(30),
DIRECTOR VARCHAR(30),
DURATION INT
);
--- CHECK TABLE DESCRIPTION
--- SYNTAX: DESCRIBE TABLENAME
DESCRIBE MOVIE_TABLE;




