USE SCHOOL;
CREATE TABLE STUDENTS_DATA(
   ID INT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(30) NOT NULL,
   GENDER VARCHAR(10),
   CLASS INT);
DESCRIBE STUDENTS_DATA;
--- ALTER COMMAND
--- ADD NEW AGE COLUMN
--- SYNTAX: ALTER TABLE TABLENAME ADD COLUMN COL_NAME DATATYPE [CONSTRAINSTS]
ALTER TABLE STUDENTS_DATA ADD COLUMN AGE TINYINT; 
DESCRIBE STUDENTS_DATA;
ALTER TABLE STUDENTS_DATA ADD COLUMN DOB DATE;
DESCRIBE STUDENTS_DATA;
ALTER TABLE STUDENTS_DATA ADD COLUMN AGE TINYINT CHECK(AGE>5); 
DESCRIBE STUDENTS_DATA;
ALTER TABLE STUDENTS_DATA ADD COLUMN LOCATION VARCHAR(50), ADD COLUMN ADDRESS VARCHAR(30);
DESCRIBE STUDENTS_DATA;
--- DELETE COLUMN
--- SYNTAX: ALTER TABLE TABLE_NAME DROP COLUMN COL_NAME;
--- DELETE AGE
ALTER TABLE STUDENTS_DATA DROP COLUMN AGE;
DESCRIBE STUDENTS_DATA;
ALTER TABLE STUDENTS_DATA ADD COLUMN AGE TINYINT CHECK(AGE>5);
DESCRIBE STUDENTS_DATA;

-- CHANGE ID TO COLUMN NAME STDID
ALTER TABLE STUDENTS_DATA RENAME COLUMN ID TO STDID;
DESCRIBE STUDENTS_DATA;

-- CHANGE GENDER COLUMN DATATYPE
-- SYNTAX: ALTER TABLE TABLE_NAME MODIFY COLUMN COL_NAME DATATYPE[CONSTRAINTS];
DESCRIBE STUDENTS_DATA;
DROP TABLE STUDENTS;

