USE SCHOOL;
DESC STUDENTS;
INSERT INTO STUDENTS VALUES(01,"CHINNI","fEMALE",4);
DESC STUDENTS;
INSERT INTO STUDENTS (STD_ID,STD_NAME,GNDER,CLASS) VALUES(02,"VEGI","MALE",5),(03,"CHANDU","MALE",6);
DESCRIBE STUDENTS;
SELECT * FROM STUDENTS;
USE SCHOOL;
ALTER TABLE STUDENTS RENAME COLUMN GNDER TO GENDER;
DESCRIBE STUDENTS;
ALTER TABLE STUDENTS MODIFY GENDER ENUM("FEMALE","MALE");
DESCRIBE STUDENTS;
--- INSERTING DATA TO MARKS TABLE
INSERT INTO MARKS (STD_ID,S1,S2,S3,PERCENTAGE) VALUES(1,97,88,95,96.00),(2,98,78,95,98.00);
DESCRIBE MARKS;
SELECT * FROM MARKS;
INSERT INTO MARKS (STD_ID,S1,S2,S3,PERCENTAGE) VALUES(5,88,99,55,96.000);
SELECT * FROM MARKS;
--- UPDATE 5 MARKS FOR 1 STUDENT FOR S1 SUBJECT
SELECT * FROM MARKS
WHERE STD_ID=1;
UPDATE MARKS SET S1=S1+5
WHERE STD_ID=1;
SELECT * FROM MARKS;

-- UPDATE 5 MARKS FOR 2 STUDENT FOR S1 AND S2
SELECT * FROM MARKS
WHERE STD_ID=2;
UPDATE MARKS SET S1=S1+5,S2=S2+5;
SELECT * FROM MARKS
WHERE STD_ID=2;
SET SQL_SAFE_UPDATES=0

--- UPDATE PERCENTAGE COLUMN AS DERIVED COLUMN
ALTER TABLE MARKS MODIFY COLUMN PERCENTAGE FLOAT(5,2) GENERATED ALWAYS AS ((S1+S2+S3)/3) STORED;
UPDATE  MARKS SET S1=S1+5,S2=S2+5,S3=S3+5
WHERE STD_ID=1;
SELECT * FROM MARKS;
ALTER TABLE MARKS ADD COLUMN TOTAL INT GENERATED ALWAYS AS (S1+S2+S3) STORED AFTER S3;
SELECT * FROM MARKS;
SELECT * FROM STUDENTS;
INSERT INTO STUDENTS VALUES("4","JAANU","FEMALE","5"),("5","RAMYA","FEMALE","6");
INSERT INTO STUDENTS VALUES("6","HONEY","FEMALE","6");
SELECT * FROM MARKS;
SELECT * FROM STUDENTS;

ALTER TABLE STUDENTS ADD COLUMN AGE TINYINT NOT NULL;

-- SELECT NAME NAME ID FOR CREATING NEW DATA
SELECT STD_ID,STD_NAME FROM STUDENTS;

