-- correlated subquery
-- get the employee details whose salary is greater than their dept's average salary
USE IT_COMPANY;
SELECT * FROM EMPLOYEES E1
WHERE SALARY>(SELECT AVG(SALARY)  FROM EMPLOYEES E2 WHERE E1.DEPT=E2.DEPT);

-- GET THE EACH DEPT MAXIMUM SALARY EMPLOYEE DETAILS
SELECT * FROM EMPLOYEES E1
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEES E2 WHERE E1.DEPT=E2.DEPT);