CREATE DATABASE TIPS_ANALYSIS;
USE TIPS_ANALYSIS;
SELECT * FROM TIPS;
DESCRIBE TIPS;

--- CHANGE SEX COLUMN NAME AS GENDER
ALTER TABLE TIPS RENAME COLUMN SEX TO AGE;
DESCRIBE TIPS;

-- 1. GET FEMALE RECORDS
-- 2. FIND MALE RECORDS
-- 3. FIND DINNER TIME FEMALE RECORDS
-- 4. FIND THE SIZE 2 RECORDS
SELECT * FROM TIPS 
WHERE SIZE=2;
-- 5. FIND MALE SMOKER RECORDS
SELECT * FROM TIPS 
WHERE GENDER="MALE" AND SMOKER="YES";
-- 6. GET THE NON SMOKER FEMALE RECORDS
-- 7. GET THE DINNER TIME MALE RECORD
-- 8. GET THE FEMALE RECORDS IN DESCENDING ORDER AS PER THE TOTAL_BILL
SELECT * FROM TIPS
WHERE GENDER="FEMALE"
ORDER BY TOTAL_BILL DESC;
-- 9. GET THE TOP 5 MALE TOTAL_BILLS
SELECT * FROM TIPS 
WHERE GENDER="MALE"
ORDER BY TOTAL_BILL DESC
LIMIT 5;
SELECT * FROM TIPS;
-- 10. GET BOTHE SIZE 2 AND 3 RECORDS
SELECT * FROM TIPS
WHERE SIZE=2 OR SIZE=3;
-- 11. GET THE RECORDS WHOSE TOTAL BILL IN THE RANGE OF 10 TO 20
SELECT * FROM TIPS 
WHERE 10<=TOTAL_BILL AND TOTAL_BILL<=20;
SELECT * FROM TIPS 
WHERE TOTAL_BILL BETWEEN 10 AND 20;
-- 12. GET ALL SIZE 2,3AND 4 RECORDS
SELECT * FROM TIPS 
WHERE SIZE IN (2,3,4);



--- 1. GET FEMALE RECORDS
SELECT * FROM TIPS
WHERE AGE = "Female";

--- 2. FIND MALE RECORDS
SELECT * FROM TIPS
WHERE AGE="Male";

--- 3. FIND DINNER TIME FEMALE RECORDS

SELECT * FROM TIPS
WHERE TIME="Dinner" AND GENDER="Female"; 

--- 4. FIND THE SIZE 2 RECORDS
SELECT * FROM TIPS
WHERE SIZE=2;

--- 5. FIND MALE SMOKER RECORDS
SELECT * FROM TIPS
WHERE GENDER="Male" AND SMOKER="YES";

-- 6. GET THE NON SMOKER FEMALE RECORDS
SELECT * FROM TIPS
WHERE SMOKER="NO" AND GENDER="Female";

ALTER TABLE TIPS RENAME COLUMN AGE TO GENDER;
SELECT * FROM TIPS;

-- 7. GET THE DINNER TIME MALE RECORDS
SELECT * FROM TIPS 
WHERE TIME="Dinner" AND GENDER="Male";

-- 8. GET THE FEMALE RECORDS IN DESCENDING ORDER AS PER THE TOTAL_BILL
SELECT * FROM TIPS
WHERE GENDER="Female"
ORDER BY TOTAL_BILL DESC;

--- 9. GET THE TOP 5 MALE TOTAL_BILLS
SELECT * FROM TIPS
WHERE GENDER ="Male"
ORDER BY TOTAL_BILL DESC
LIMIT 5;

-- 10. GET BOTHE SIZE 2 AND 3 RECORDS
SELECT * FROM TIPS
WHERE SIZE=2 OR SIZE=3;

-- 11. GET THE RECORDS WHOSE TOTAL BILL IN THE RANGE OF 10 TO 20
SELECT * FROM TIPS
WHERE TOTAL_BILL>=10 AND TOTAL_BILL<=20;
 
SELECT *FROM TIPS
WHERE TOTAL_BILL BETWEEN 10 AND 20;

-- 12. GET ALL SIZE 2,3AND 4 RECORDS 
SELECT * FROM TIPS
WHERE SIZE=2 OR SIZE=3 OR SIZE=4;

SELECT * FROM TIPS
WHERE SIZE IN (2,3,4);

-- SLECT TOP 2 ND HIGHEST TOTAL_BILL

SELECT * FROM TIPS
ORDER BY TOTAL_BILL DESC
LIMIT 1 OFFSET 1;

SELECT * FROM TIPS
ORDER BY TOTAL_BILL DESC
LIMIT 3 OFFSET 2;


-- 1. RETURN TOTAL RECORDS IN TIPS TABLE
-- 2. RETURN TOTAL MALE SMOKER COUNT
-- 3. RETURN TOTAL TIP
-- 4. RETURN FEMALE NON SMOKER COUNT
-- 5. RETURN MINIMUM AN MAXIMUM TOTAL BILL


-- RETURN TOTAL RECORDS IN TIPS TABLE 
USE TIPS_ANALYSIS;
SELECT COUNT(*) FROM TIPS;

-- 2. RETURN TOTAL MALE SMOKER COUNT
SELECT COUNT(*) FROM TIPS 
WHERE GENDER="Male" AND SMOKER="YES";

-- 3. RETURN TOTAL TIP 
SELECT SUM(TIP) FROM TIPS;

-- 4. RETURN FEMALE NON SMOKER COUNT
SELECT COUNT(*) FROM TIPS
WHERE GENDER="Female" AND SMOKER="YES";

-- 5. RETURN MINIMUM AN MAXIMUM TOTAL BILL
SELECT MIN(TOTAL_BILL),MAX(TOTAL_BILL) FROM TIPS;

select count(*) from tips
where gender="Female";

-- FIND THE TOTAL SUNDAY RECORDS COUNT
-- GET THE SATURDAY AND SUNDAY RECORDS COUNT
--       GROUP BY QUEIRES
-- 1 GET THE GENDER COLUM UNIQUE VALUES
-- 2 GET THE DINNER TIME RECORDS COUNT
-- 3 GET THE TOTAL RECORDS COUNT AS PER THE GENDER COLUMN
-- 4 GET THE SMOKER AND NON SMOKR COUNT
-- 5 GET THE SUNDAY TOTAL RECORDS COUNT AS PER THE GENDER COLUMN
-- 6 GET THE SIZE 2 TOTAL COUNT AS PER THE GENDER
-- 7 GET THE EACH SIZE COUNT IN DESCENDING ORDER
SELECT SIZE,COUNT(*) FROM TIPS 
GROUP BY SIZE
ORDER BY SIZE DESC;
-- 8 GET THE SIZE 2,3 AND 4 SMOKER AND NON SMOKER COUNT
-- 9 GET THE EACH  SIZE COUNT AS PER THE GENDER
-- 10 FIND THE EACH SIZE MAX AND MIN TOTAL_BILL
-- 11 FIND THE MALE TOTAL RECORDS AS PER THE DAY IN DESCENDING


SELECT * FROM TIPS;
SELECT COUNT(*) FROM TIPS
WHERE DAY="Sun";

-- GET THE SATURDAY AND SUNDAY RECORDS COUNT

SELECT DAY,COUNT(*) FROM TIPS
GROUP BY DAY
LIMIT 2;

-- 1 GET THE GENDER COLUM UNIQUE VALUES
SELECT GENDER FROM TIPS
GROUP BY GENDER;

-- 2 GET THE DINNER TIME RECORDS COUNT
SELECT COUNT(*) FROM TIPS
WHERE TIME="Dinner";

-- 3 GET THE TOTAL RECORDS COUNT AS PER THE GENDER COLUMN
SELECT COUNT(GENDER) FROM TIPS;
SELECT GENDER ,COUNT(*) FROM TIPS
GROUP BY GENDER;

-- 4 GET THE SMOKER AND NON SMOKR COUNT
SELECT SMOKER,COUNT(*) FROM TIPS
GROUP BY SMOKER;

-- 5 GET THE SUNDAY TOTAL RECORDS COUNT AS PER THE GENDER COLUMN
SELECT * FROM TIPS;
SELECT DAY,GENDER,COUNT(*) FROM TIPS
WHERE DAY="SUN"
GROUP BY GENDER;

-- 6 GET THE SIZE 2 TOTAL COUNT AS PER THE GENDER
SELECT GENDER,COUNT(*) FROM TIPS 
WHERE SIZE=2
GROUP BY GENDER;

-- 7 GET THE EACH SIZE COUNT IN DESCENDING ORDER
SELECT SIZE,COUNT(*) FROM TIPS 
GROUP BY SIZE
ORDER BY SIZE DESC;

-- 8 GET THE SIZE 2,3 AND 4 SMOKER AND NON SMOKER COUNT
SELECT SMOKER,COUNT(*) FROM TIPS
WHERE SIZE IN (2,3,4)
GROUP BY SMOKER;


-- 9 GET THE EACH  SIZE COUNT AS PER THE GENDER
SELECT SIZE,GENDER,COUNT(*) FROM TIPS
GROUP BY SIZE,GENDER
ORDER BY SIZE ASC,COUNT(*) DESC;

-- 10 FIND THE EACH SIZE MAX AND MIN TOTAL_BILL
SELECT SIZE,MIN(TOTAL_BILL),MAX(TOTAL_BILL) FROM TIPS
GROUP BY SIZE;

-- 11 FIND THE MALE TOTAL RECORDS AS PER THE DAY IN DESCENDING
SELECT DAY,COUNT(*) FROM TIPS 
WHERE GENDER="MALE"
GROUP BY DAY 
ORDER BY COUNT(*) DESC;



SELECT DISTINCT GENDER FROM TIPS;
SELECT SIZE,COUNT(*) FROM TIPS 
GROUP BY SIZE ;

-- RETURN THE SIZE WHICH ONE TOTAL_COUNT IS GREATE THAN 30
SELECT SIZE,COUNT(*) FROM TIPS
GROUP BY SIZE
HAVING COUNT(*)>30
ORDER BY SIZE;

-- GET THE EACH SIZE GENDER COUNT WHICH IS MORE THAN 20
SELECT SIZE,GENDER,COUNT(*) FROM TIPS
GROUP BY GENDER,SIZE
HAVING COUNT(*)>20;

-- GET THE SIZES WHICH IS MAXIMUM TOTAL_BILL AND MINIMUM TOTAL_BILL DIFFERENCE IS LESSER THAN 10
SELECT SIZE,MIN(TOTAL_BILL),MAX(TOTAL_BILL),(MAX(TOTAL_BILL)-MIN(TOTAL_BILL)) FROM TIPS 
GROUP BY SIZE
HAVING MAX(TOTAL_BILL)-MIN(TOTAL_BILL)>20;


-- 1. GET FEMALE RECORDS
use tips_analysis;
SELECT * FROM TIPS;
SELECT * FROM TIPS
WHERE GENDER="MALE";

-- 3. FIND DINNER TIME FEMALE RECORDS
SELECT * FROM TIPS
WHERE TIME="DINNER" AND GENDER="FEMALE";

-- 6 GET THE SIZE 2 TOTAL COUNT AS PER THE GENDER
SELECT GENDER,COUNT(*) FROM TIPS 
WHERE SIZE=2
GROUP BY GENDER;

